#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  
  # I aspire to let the data talk and make an impact.

  Two years ago, working towards a Bachelor’s degree in Economics, I took a summer elective course *Introduction to Machine Learning*. That is how my data analytics journey began.
  
  
  Fast-forwarding to the present, I find myself with a Master Science degree in Business Analytics from Emory University and plenty of valuable experiences in the data analytics field. I remember how excited I was seeing the impact my analysis makes on pricing as a Data Analytics intern at Yum! Brands. Even the details of the endless nights at Goizueta Business School I spent with teammates on *Marketing Analytics* projects are still vivid. I believe these experiences have made me love data more, enhanced my data expertise and will eventually lead to a professional data-driven career. I would love to share some projects I worked on to spread the charm of data analytics!
  
  
  A little more about myself… I love challenges and always exploring new things! Exploring the world is one of my hobbies. Outdoor activities such as hiking, surfing and fishing are my favorites :)
  
contact: >
  # Contact

  Feel free to connect with me on LinkedIn! You may also contact me [through my email](mailto:chengzhangj@gmail.com) if you would be interested in further discussions on the projects :)

#-------------------------------
# Work Section

projects:
- {name: 'Marketing Analytics', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Data Visualization', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Sports Analytics', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Machine Learning', folder: 'proj-4', file: 'projects/proj-4.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/chengzhang-jiang'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/chengzhang-jiang/'}
- {icon: 'envelope', link: 'mailto:chengzhangj@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
